title: "Huihui Song"
author: "Huihui Song"
description: "University of Liverpool"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_excerpts: true
show_frame: true
show_sidebar: true
minimal: false

# Menu
navigation:
  - {file: "/huihui.pdf", title: "CV", icon: home}
  - {title: "About me", icon: address-card}

external:
  - {title: Mail, icon: envelope, url: "mailto:hss6c@liverpool.ac.uk"}
  - {title: Github, icon: github, url: "https://github.com/hhssong"}

comments:
  # disqus_shortname: ""
  # isso_domain: ""

plugins:
  - jekyll-feed
